default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  pool: 5
  host: localhost
  database: geri
  username: postgres
  password: 123

test:
  <<: *default
  pool: 5
  host: localhost
  database: geri_test
  username: postgres
  password: 123


production:
  <<: *default
